[package]
name = "logged_tcp_proxy"
version = "0.1.1"
edition = "2021"
authors = ["Alexandr Garbuzov <qwerty541zxc@gmail.com>"]
description = "Command line interface for proxying TCP connections with payload output into console which can be formatted different ways."
keywords = ["network", "tcp", "proxy", "logging", "debugging"]
categories = [
    "command-line-utilities",
    "development-tools::debugging",
    "network-programming"
]
license = "MIT OR Apache-2.0"
repository = "https://github.com/qwerty541/logged-tcp-proxy"
homepage = "https://github.com/qwerty541/logged-tcp-proxy"
readme = "README.md"
exclude = [".github", ".vscode", ".gitignore"]

[dependencies]
bytes = "1.4.0"
clap = { version = "4.3.0", features = ["std", "derive"] }
env_logger = "0.10.0"
logged-stream = "0.3.0"
log = "0.4.18"
tokio = { version = "1.28.2", features = [
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "time"
], default-features = false }
