[package]
name = "logged_tcp_proxy"
version = "0.1.0"
edition = "2021"
authors = ["Alexandr Garbuzov <qwerty541zxc@gmail.com>"]
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
bytes = "1.4.0"
env_logger = "0.10.0"
lazy_static = "1.4.0"
logged-stream = "0.2.1"
log = "0.4.17"
tokio = { version = "1.27.0", features = [
    "io-util",
    "macros",
    "net",
    "rt-multi-thread",
    "time"
], default-features = false }
